### ISSUE TITLE
openjscad.ts TS2394 overload signature

### ISSUE THREAD

**Issue by rienafairefr** [Microsoft/maker.js#279]
Well, there is still a compiling error using 2.4 typescript version:

src/core/openjscad.ts(133,21): error TS2394: Overload signature is not compatible with function implementation.

It's something that has been added between typescript 2.4.0 and typescript 2.4.1 AFAIK, makerjs compiles with 2.4.0 but not 2.4.1
